[workspace]
members = ["libs/axum-socket-io"]

[package]
name = "web-socket-io"
version = "0.1.0"
edition = "2021"

[dependencies]
web-socket = "0.7"
tokio = { version = "1", features = ["sync", "rt"] }
